name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install required packages
      run: sudo apt-get -y install ocaml ocaml-dune pandoc
    - name: Build
      run: dune build
    - name: Test
      run: dune runtest
    - name: Build doc
      run: make -C docs && rm -f docs/.gitignore
    - name: Upload website artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2
