name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.0.x
    - name: Install required packages
      run: sudo apt-get -y install pandoc
    - name: Pin locally
      run: opam pin -y add -n .
    - name: Build and test
      run: opam install -y -t odoc js_of_ocaml js_of_ocaml-ppx alg
    - name: Build doc
      run: eval $(opam env) && make -C docs && rm -f docs/.gitignore
    - name: Upload website artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v2
